### PR TITLE
Fixing default DateTime bug with TimeZones

### LINKED ISSUE #2971: Type conversion error for myTimer occurs for the first time after every release of dotnet-isolated
### What version of .NET does your existing project use?

.NET 6

### What version of .NET are you attempting to target?

.NET 8

### Description

```
Error converting 1 input parameters for Function 'XXX': Cannot convert input parameter 'myTimer' to type 'Microsoft.Azure.Functions.Worker.TimerInfo' from type 'System.String'. Error:System.Text.Json.JsonException: The JSON value could not be converted to System.DateTime. Path: $.ScheduleStatus.Last | LineNumber: 0 | BytePositionInLine: 86.
 ---> System.FormatException: The JSON value is not in a supported DateTime format.
   at System.Text.Json.ThrowHelper.ThrowFormatException(DataType dataType)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.DateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Microsoft.Azure.Functions.Worker.Extensions.Timer.Converters.TimerInfoConverter.GetConversionResultFromDeserialization(Byte[] bytes) in D:\a\_work\1\s\extensions\Worker.Extensions.Timer\src\Converters\TimerInfoConverter.cs:line 52 
```

### Project configuration and dependencies

Function:
```
        [Function("FunctionName")]
        public void RunDataAccumulation([TimerTrigger("%XXXSchedule%")] TimerInfo myTimer)
        {
         ...
        }
```

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enabled</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.1" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
	<PackageReference Include="Microsoft.Azure.Core.NewtonsoftJson" Version="2.0.0" />
	<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
```

host.json:
```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "logging": {
    "fileLoggingMode": "debugOnly",
    "logLevel": {
      "default": "Debug",
      "Host": "Debug",
      "Host.Aggregator": "Debug"
    },
    "applicationInsights": {
      "enableDependencyTracking": true,
      "enablePerformanceCountersCollection": true,
      "DependencyTrackingOptions": {
        "enableSqlCommandTextInstrumentation": true
      },
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "worker": {
    "description": {
      "defaultExecutablePath": "dotnet",
      "defaultWorkerPath": "dotnet",
      "arguments": [
        "%FUNCTIONS_WORKER_PATH%"
      ]
    }
  }
}
```

local.settings.json:
```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": xxx
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "FUNCTIONS_INPROC_NET8_ENABLED": 1,
    "XXXSchedule": "0 */1 * * * *",
    "WEBSITE_TIME_ZONE": "Tokyo Standard Time",
  }
}
```

### Link to a repository that reproduces the issue

_No response_

### PR DESCRIPTION
**Pull request by brettsam**
Fixes https://github.com/Azure/azure-functions-dotnet-worker/issues/2971 

There was an issue with us using a default `DateTime` that, when parsed by certain Json serializers would throw an exeption (notably `System.Text.Json` in .NET... although `Newtonsoft.Json` worked fine)

This is because using `new DateTime(0, DateTimeKind.Local)` results in a usable `DateTime`, but when cast or parsed as a `DateTimeOffset`, would throw.

This change fixes that and adds a bunch of tests around the scenarios we were seeing. It also adds an additional detail to the TriggerDetails collection, which would have helped us in our analysis.

### CODE REVIEW

File: src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs [hunk 1]
```diff
@@ -14,7 +14,12 @@ namespace Microsoft.Azure.WebJobs.Extensions.Timers
     /// </summary>
     public abstract class ScheduleMonitor
     {
-        private static DateTime defaultDateTime = new DateTime(0, DateTimeKind.Local);
```
Comment (brettsam) [inline src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs:17]: This was ultimately the bug

File: src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs [hunk 2]
```diff
@@ -14,7 +14,12 @@ namespace Microsoft.Azure.WebJobs.Extensions.Timers
...
+        // Avoid anything close to DateTime.MinValue as time zone conversions have caused bugs
+        internal static readonly DateTime DefaultDateTime = default(DateTime).ToLocalTime().AddYears(1);
```
Comment (liliankasem) [inline src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs]: Do we know if this would cause any breaking changes somewhere? Does anywhere in Functions/Antares depend on the MinValue ?

File: src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs (hunk 1 above)
Comment (liliankasem) [reply src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs:17]: argh

File: src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs (hunk 2 above)
Comment (brettsam) [reply src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs]: Good callout. We went back to MinValue just to be safe.

**Review by fabiocav — APPROVED** [review]

**Review by liliankasem — APPROVED** [review]
